services:
  web:
    build: ./django-rest-api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django-rest-api/:/usr/src/django-rest-api/
    ports:
      - 8000:8000
      - 3000:3000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data: