# Generated by Django 4.2.3 on 2024-05-27 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='', verbose_name='audios/')),
                ('name', models.CharField(max_length=200)),
                ('duration', models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AudioTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_library_api.audio')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_library_api.playlist')),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='audios',
            field=models.ManyToManyField(through='music_library_api.PlaylistAudio', to='music_library_api.audio'),
        ),
        migrations.AddField(
            model_name='audio',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music_library_api.playlist'),
        ),
        migrations.AddField(
            model_name='audio',
            name='artists',
            field=models.ManyToManyField(related_name='audios', to='music_library_api.artist'),
        ),
        migrations.AddField(
            model_name='audio',
            name='tags',
            field=models.ManyToManyField(related_name='audios', to='music_library_api.audiotag'),
        ),
        migrations.AddField(
            model_name='artist',
            name='albums',
            field=models.ManyToManyField(related_name='album_artists', to='music_library_api.playlist'),
        ),
    ]
