# Generated by Django 4.2.3 on 2024-05-29 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_library_api', '0003_alter_audio_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio_file',
            field=models.FileField(upload_to='', verbose_name='audios/'),
        ),
    ]
