# Generated by Django 4.2.3 on 2024-05-31 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_library_api', '0004_alter_audio_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
        migrations.AlterField(
            model_name='audiotag',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
